
name: Go
on: [push]
jobs:

  build-linux:
    name: "Build on Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Make build
        run: /bin/sh ./build-linux.sh
      - name: Upload Debian pacakge
        uses: actions/upload-pages-artifact@v3
        with:
          name: golden-linux-amd64
          path: golden-linux-amd64
