
name: Go
on: [push]
jobs:

  build-windows-amd64:
    name: "Build on Windows x86_64"
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Make build
        run: powershell -executionpolicy RemoteSigned -file "./build-windows-amd64.ps1"
      - name: Upload Windows executable
        uses: actions/upload-artifact@v1
        with:
          name: golden-windows-amd64
          path: golden-windows-amd64.exe


  build-windows-386:
    name: "Build on Windows x86"
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Make build
        run: powershell -executionpolicy RemoteSigned -file "./build-windows-386.ps1"
      - name: Upload Windows executable
        uses: actions/upload-artifact@v1
        with:
          name: golden-windows-386
          path: golden-windows-386.exe


  build-linux:
    name: "Build on Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Make build
        run: /bin/sh ./build-linux.sh
      - name: Upload Debian pacakge
        uses: actions/upload-artifact@v1
        with:
          name: golden-linux-amd64
          path: golden-linux-amd64

  build-macos:
    name: "Build on macOS X"
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Make build
        run: /bin/sh ./build-darwin.sh
      - name: Upload macOS disk image
        uses: actions/upload-artifact@v1
        with:
          name: golden-darwin-amd64
          path: golden-darwin-amd64
